#!/bin/env bash
#
# 7z needs to be installed able to be used from the command line in order to
# compress files:
#
# sudo apt install p7zip-full
#
# Compressed file created with:
#
# 7z a clean_data.csv.7z clean_data.csv
#

INPUT_FILE=clean_data.csv.7z
OUTPUT_FILE=clean_data.csv

echo "Decompress clean_data.csv"

ls -l "${OUTPUT_FILE}"

#
# TODO: Check that 7z is available
#
#
# TODO: Check if the file exists before decompressing
#

echo
echo "Listing compressed file contents:"
echo
7z l "${INPUT_FILE}"

echo
echo "Extract ${OUTPUT_FILE} from ${INPUT_FILE}:"
echo
7z x "${INPUT_FILE}" "${OUTPUT_FILE}"
